
version: baseline

agent:
  q_initialization: random
  seed: 1
  epsilon: 0.05
  gamma: .98
  alpha: 0.01

training:
  n_steps: 1e7

environment:
  name: gridworld
  config:
    height: 20
    width: 10
    rewards:    # amount, x, y
      - [1, 0, 5]
      - [1, 10, 1]
    randstart: true

logging:

